services:
  db:
    image: postgres:16
    container_name: pycolors-marketing-db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pycolors_marketing
    volumes:
      - pycolors_marketing_data:/var/lib/postgresql/data

volumes:
  pycolors_marketing_data: