// @ts-nocheck
import { default as __fd_glob_41 } from "../content/docs/saas-starter/meta.json?collection=docs"
import * as __fd_glob_40 from "../content/docs/ui/toast.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/ui/tabs.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/ui/table.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/ui/skeleton.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/ui/sheet.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/ui/password-input.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/ui/pagination.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/ui/input.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/ui/index.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/ui/empty-state.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/ui/dropdown-menu.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/ui/dialog.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/ui/card.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/ui/button.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/ui/badge.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/ui/alert.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/design-system/tokens/shadows.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/design-system/tokens/radius.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/design-system/tokens/index.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/saas-starter/upgrade-to-pro.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/saas-starter/project-structure.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/saas-starter/installation.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/saas-starter/index.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/saas-starter/getting-started.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/saas-starter/deployment.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/saas-starter/billing-concept.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/saas-starter/auth-concept.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/patterns/overlays.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/patterns/index.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/patterns/data-table.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/patterns/async-actions.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/guides/index.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/guides/forms-with-validation.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/guides/empty-loading-error.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/guides/building-a-saas-layout.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/design-system/typography.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/design-system/index.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/design-system/colors.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/why-pycolors-ui.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/release-policy.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/index.mdx?collection=docs"
import { fromConfig } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = fromConfig<typeof Config>();

export const docs = await create.docs("docs", "content/docs", {"saas-starter/meta.json": __fd_glob_41, }, {"index.mdx": __fd_glob_0, "release-policy.mdx": __fd_glob_1, "why-pycolors-ui.mdx": __fd_glob_2, "design-system/colors.mdx": __fd_glob_3, "design-system/index.mdx": __fd_glob_4, "design-system/typography.mdx": __fd_glob_5, "guides/building-a-saas-layout.mdx": __fd_glob_6, "guides/empty-loading-error.mdx": __fd_glob_7, "guides/forms-with-validation.mdx": __fd_glob_8, "guides/index.mdx": __fd_glob_9, "patterns/async-actions.mdx": __fd_glob_10, "patterns/data-table.mdx": __fd_glob_11, "patterns/index.mdx": __fd_glob_12, "patterns/overlays.mdx": __fd_glob_13, "saas-starter/auth-concept.mdx": __fd_glob_14, "saas-starter/billing-concept.mdx": __fd_glob_15, "saas-starter/deployment.mdx": __fd_glob_16, "saas-starter/getting-started.mdx": __fd_glob_17, "saas-starter/index.mdx": __fd_glob_18, "saas-starter/installation.mdx": __fd_glob_19, "saas-starter/project-structure.mdx": __fd_glob_20, "saas-starter/upgrade-to-pro.mdx": __fd_glob_21, "design-system/tokens/index.mdx": __fd_glob_22, "design-system/tokens/radius.mdx": __fd_glob_23, "design-system/tokens/shadows.mdx": __fd_glob_24, "ui/alert.mdx": __fd_glob_25, "ui/badge.mdx": __fd_glob_26, "ui/button.mdx": __fd_glob_27, "ui/card.mdx": __fd_glob_28, "ui/dialog.mdx": __fd_glob_29, "ui/dropdown-menu.mdx": __fd_glob_30, "ui/empty-state.mdx": __fd_glob_31, "ui/index.mdx": __fd_glob_32, "ui/input.mdx": __fd_glob_33, "ui/pagination.mdx": __fd_glob_34, "ui/password-input.mdx": __fd_glob_35, "ui/sheet.mdx": __fd_glob_36, "ui/skeleton.mdx": __fd_glob_37, "ui/table.mdx": __fd_glob_38, "ui/tabs.mdx": __fd_glob_39, "ui/toast.mdx": __fd_glob_40, });